export default function Outreach() {
  return (
    <div className="max-w-3xl">
      <p>Within my research groups, I have mentored several undergraduate students on independent research projects and have led laboratory tours and information sessions for prospective students in hopes of increasing diversity within my labs and the Physics department.</p>
      <p>As a Berkeley Connect Fellow, I facilitated informal small-group discussions about topics related to physics and mentored ~40 students per semester, providing guidance and support as they navigated the transition to college and paths to success in Berkeley Physics. Through this opportunity to serve as a role model and guide, I helped students primarily from underrepresented and nontraditional backgrounds get the most out of their undergraduate experience at Berkeley, while further developing my mentorship skills.</p>
      <br></br>
      <p>At Cornell, my experience as an educator began in the spring of my freshman year through <i>Teaching and Learning Physics</i>, a course in which I gained effective teaching and communication practices. Alongside this, I was an Undergraduate Teaching Assistant from Spring 2016 to Spring 2018, where I employed those methods in leading flipped-classroom lectures and discussion sections for several physics courses, resulting in above-average class performance. Concurrently, I mentored and tutored under-served students in nearby districts, helping them prepare college and scholarship applications.</p>
      <br></br>
      <p>As Cornell&apos;s Women in Physics (WiP) Liaison from 2017 to 2019, I collaborated with physics department officials to implement measures to increase representation of marginalized groups within the major. Working closely with the Director of Undergraduate Studies, I helped establish the Physics Peer Advising Program. As a peer mentor, I helped nearly 20 incoming students from varied backgrounds navigate their first years in the undergraduate physics community. My role as WiP Liason also provided me with a platform to engage the local community to advance accessibility and science education by coordinating events such as the annual Carl Sagan Planet Walk and Expanding Your Horizons STEM conference for middle school girls. Having experienced firsthand the lack of support systems available to underrepresented groups, I felt compelled to improve community spaces and create inclusive programming, establishing open collaborative study spaces for physics students of all levels and hosting events to bring members of these groups together. Additionally, I served on a committee which oversaw changes to the physics major and course offerings, implementing measures to reduce barriers to entry for students from disadvantaged and minority backgrounds. Through these efforts, enrollment and retention of traditionally underrepresented groups in the major more than tripled during my time as WiP Liaison.</p>
    </div>
  );
}
